### ISSUE TITLE
在预留的Cookie填入token

### ISSUE THREAD

**Issue by halftequila** [wing-ho/ximalaya#6]
ts-1641675287766开始下载！node:internal/validators:119
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received null
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.basename (node:path:1309:5)
    at new File (/Users/kai/Downloads/ximalaya-master/index.js:64:24)
    at File.getMediaFile (/Users/kai/Downloads/ximalaya-master/index.js:168:17)
    at File.transition (/Users/kai/Downloads/ximalaya-master/index.js:217:14)
    at StateMachine.transition (/Users/kai/Downloads/ximalaya-master/index.js:284:10)
    at StateMachine.dequeue (/Users/kai/Downloads/ximalaya-master/index.js:278:8)
    at Timeout._onTimeout (/Users/kai/Downloads/ximalaya-master/index.js:262:10)
    at listOnTimeout (node:internal/timers:557:17) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by wing-ho** [comment]
@KaiHLi 不好意思，我没有VIP账号，无法进行测试，更改了获取MP3的方式之后，原来的认证方式也失效了。需要使用另外的接口认证。

**Comment by lovelykid** [comment]
现在可以通过填写自己的cookie下载已购的专辑了吗？

**Comment by pashangshangpo** [comment]
我填写了cookie发现用不了，看了一下vip的音频获取方式不一样，最后找了个这个 [喜马拉雅会员VIP专辑解析下载器](https://software.jscs.top/archives/%E6%9C%80%E6%96%B0%E5%8F%AF%E7%94%A82022%E5%96%9C%E9%A9%AC%E6%8B%89%E9%9B%85fm%E9%9F%B3%E9%A2%91vip%E4%B8%93%E8%BE%91%E4%B8%8B%E8%BD%BD%E5%99%A8) 下载的vip音频

**Comment by wing-ho** [comment]
@lovelykid @KaiHLi @pashangshangpo 已支持vip用户下载
